### ISSUE TITLE
I'm having a problem downloading text

### ISSUE THREAD

**Issue by dkl3** [michaelnmmeyer/scribd_dl#2]
Hi, I want to use this script to download non-copyrighted documents from Scribd, but the problem is I can download the images but not the text with it.

**Comment by michaelnmmeyer** [comment]
Can you send me an example link?

**Comment by dkl3** [comment]
Oh, sorry, I forgot to say that. Well, I wanted to try and find an example one after reading your post but now when I try and use the program, this exact thing happens: 

http://pastebin.com/T2zwuUPh

I can try another Scribd document. The same thing still happens: http://pastebin.com/SiyA0yNg

So please help me with this issue first. This didn't happen yesterday but only started today. Thanks.

**Comment by michaelnmmeyer** [comment]
I tried to add support for downloading PDFs with embedded text. This requires reverse-engineering Scribd's rendering code. Brittle at best, too much fuss for me.

You can try [this script](https://github.com/tobiasBora/Scribd-downloader/blob/master/scribd_download.sh) . It seems to (partly) work for this kind of files.
